language: bash
dist: trusty
group: travis_latest
sudo: required

if: |
  branch = master AND \
  ! commit_message =~ /readme.md/ AND \
  ! commit_message =~ /docker-compose.yml/ OR \
  type = cron

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="mono base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="mono"
    - DOCKER_URL="https://www.mono-project.com/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"
  matrix:
    - DOCKER_TAG="latest"
      DOCKER_VERSION="$(curl -sL https://download.mono-project.com/sources/mono/ | grep 'tar.bz2' | tail -n 1 | awk -F '>mono-' {'print $2'} | awk -F '.tar.bz2' {'print $1'})"

before_install:
  - docker version
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

install:

before_script:
  - sed -i -e "/^$/d" -e "s/^[ \t]*//" -e "/^#/d" Dockerfile

script:
  - docker build --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG} --pull .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}
  # Trigger lidarr_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/mono", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Flidarr_docker/requests'
  # Trigger sonarr_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/mono", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fsonarr_docker/requests'

notifications:
  email:
    on_success: never
    on_failure: change
